Experiment 2- Write the NumPy program to save a given array to text file and load it.

In [ ]:
import numpy as np

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Creating 2D array
List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
Array = np.array(List)

In [ ]:
# Displaying the array
print('Array:\n', Array)
 

Array:
 [1 2 3 4 5 6 7 8 9]


In [ ]:
# Saving the 2D array in a text file
np.savetxt("file.txt", Array)

In [ ]:
# Displaying the contents of the text file
content = np.loadtxt('file.txt')
print("\nContent in file.txt:\n", content)


Content in file.txt:
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
np.savetxt("abc.txt",Array,fmt="%d",header="Roll_No") 

In [ ]:
a=np.loadtxt("abc.txt") 

In [ ]:
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Exp 2.1- Store the pandas DataFrame data in text file


In [ ]:
import pandas as pd

data = [1,2,3,4,5]
#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
b = df.to_numpy()

In [ ]:
np.savetxt("abcd.txt",b,fmt = "%s",header = "Roll_no")

In [ ]:
c = np.loadtxt("abcd.txt")

In [ ]:
c

array([1., 2., 3., 4., 5.])