Experiment-3      Write a NumPy
program to create a 3x3x3 array filled with arbitrary values



In [ ]:
import numpy as np


In [ ]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.66937048 0.42899037 0.81063006]
  [0.97605746 0.60722633 0.23626339]
  [0.05075536 0.52329009 0.71276774]]

 [[0.36346016 0.07490787 0.55811319]
  [0.43982685 0.70117994 0.03643763]
  [0.3627834  0.22265892 0.58116654]]

 [[0.55241394 0.32733906 0.63703477]
  [0.466425   0.07582841 0.85053286]
  [0.42111342 0.92557869 0.32156031]]]


Experimnet-4     Write a NumPy
program to convert a given array into a list and then convert it into a list
again.

In [ ]:
import numpy as np

In [ ]:
a = [[1, 2], [3, 4]]
x = np.array(a)

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
a2 = x.tolist()

In [ ]:
a2

[[1, 2], [3, 4]]