# Lab 5: Write a program for understanding different 
## tensorflow syntax and different operations

In [2]:
import tensorflow as tf


In [3]:
c = tf.constant([[1,2,3,4], [-1,-2,-3,-4], [5,6,7,8]])


In [4]:
tf.math.segment_sum(c, tf.constant([0, 0, 1]))


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [5, 6, 7, 8]], dtype=int32)>

In [5]:
x = tf.constant([-float("inf"), -9, -0.5, 1, 1.2, 200, 10000, float("inf")])


In [6]:
tf.math.cos(x)


<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([        nan, -0.91113025,  0.87758255,  0.5403023 ,  0.36235774,
        0.48718765, -0.95215535,         nan], dtype=float32)>

In [7]:
tf.math.divide(
 100,5
)


<tf.Tensor: shape=(), dtype=float64, numpy=20.0>

In [8]:
answer = tf.math.multiply(2,19)
answer


<tf.Tensor: shape=(), dtype=int32, numpy=38>

In [9]:
answer.numpy()


38

In [10]:
tf.random.normal(
 (5,2), mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None
)


<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.51248646, -1.1436448 ],
       [-0.42890853, -1.8262379 ],
       [-0.96108186,  0.5660888 ],
       [-1.1170168 , -0.29429525],
       [ 0.22761819,  1.4703304 ]], dtype=float32)>

In [12]:
my_string = tf.strings.as_string(10)
my_string


<tf.Tensor: shape=(), dtype=string, numpy=b'10'>

In [13]:
my_string.numpy()
type(my_string)

tensorflow.python.framework.ops.EagerTensor